### ISSUE TITLE
Improve rendering speed w/ caching

### ISSUE THREAD

**Issue by jones1618** [andrewstephens75/as-dithered-image#3]
Really cool component. 

Here are some quick thoughts (could be a pull-request but I just wanted to put this out there):

- How about using gray-scale images as placeholders during resizing operations? Use the browser's native (fast) rescaling for "smooth" resizing. Then, dither only when the resizing stops or is paused.
- Also, you could use the Cache API to cache the dithered versions so if the user resizes again to the same size (likely), you incur no dithering lag/cost? https://medium.com/javascript-dots/cache-api-in-javascript-644380391681

**Comment by andrewstephens75** [comment]
Hi, thanks for your feedback. I will be developing this a little more (it's actually for a larger project I have in mind) and your ideas are useful.

- I thought about placeholders but gave up on the idea. Having the image flash between greyscale and dithered would be more distracting that just a white square. Besides, it would destroy the purity of the dithered look. That said, I'll think about it some more - there might be a way to make it look better.

- The cache api looks interesting (I wasn't aware of it, thanks for introducing me) but I don't think it would be a good fit here. Resizing can produce dozens of different sizes as the user drags around the window borders, we certainly don't want to cache all of them.

I think both these issues are really rooted in the speed of the dithering process (slow). Speeding that up would make both these problems much less significant. Unfortunately, Atkinson dithering is not really suitable for hardware (WebGL) acceleration but I think there are gains to be made.

**Comment by jones1618** [comment]
What you're saying makes sense. It's your baby but, just to clarify, I wasn't suggesting you cache every intermediate sized image during resizing. I was saying if you use a placeholder for intermediate images then you'd only have cache the dithered image when resizing stops/pauses for, say 40 milliseconds or whatever.

One last thought: Instead of using a white or grayscale image of the original as a placeholder as you resize, what if you used seam carving ("smart resize") algorithm instead (see below)? You might be able to calculate several minimum carve paths as you part of your dithering pass., anyway. So, you'd render a dithered version then, while resizing use image carving to resize, then when they pause dither again.  

[Seam Carving Algorithm](https://www.analyticsvidhya.com/blog/2020/09/seam-carving-algorithm-a-seemingly-impossible-way-to-resize-an-image/)
[JS Image Carver (github)](https://trekhleb.dev/js-image-carver/)

**Comment by andrewstephens75** [comment]
Thanks again, I am reopening this issue as a catchall for ideas.

The browser itself does a pretty good job of resizing greyscale images, performance would be good if we used that as the placeholder. As I recall, there was an issue with Safari not supporting converting an ImageBuffer into an image source properly but it could probably be worked around.

Using seam carving or any resizing algorithm on dithered images will give poor results. Dithering by its nature distributes error across multiple pixels, removing any pixels crushes that error back again leaving visible artifacts.

You suggestion of pausing dithering during resize until the resizing has stopped is something I mean to do. There is no point in dithering an image during the 10ms it is on-screen during a resize operation.
