### ISSUE TITLE
Support ordered dithering?

### ISSUE THREAD

**Issue by evadecker** [andrewstephens75/as-dithered-image#9]
Hey! Having a lot of fun implementing things with this little script and I'm enjoying the results. Thanks for writing this!

Would it be possible to add [ordered/Bayer dithering](https://en.wikipedia.org/wiki/Ordered_dithering) as an option?

Ordered dithering produces "worse" results than Atkinson dithering because of the visible cross-hatch effect, but some of us (me) think that effect is cool :)

And on the plus side, ordered dithering is very fast to execute.

<img width="180" alt="image" src="https://github.com/andrewstephens75/as-dithered-image/assets/4117920/a821f234-1202-4bd5-b7e9-78b2c361d582">
<img width="180" alt="image" src="https://github.com/andrewstephens75/as-dithered-image/assets/4117920/97114c11-a1d1-489b-bd7e-fd3d7e029d7b">
<img width="180" alt="image" src="https://github.com/andrewstephens75/as-dithered-image/assets/4117920/8be25507-c34e-4a58-b5ac-f4ae786e5ee6">

**Comment by andrewstephens75** [comment]
Thank you for your suggestion. I am interested to hear what you have implemented with this component. 

Unfortunately I will probably not be adding ordered dithering myself, as Atkinson dithering meets my needs. Maybe the next time I do a big update I will squeeze it in but for now I am marking this as won't fix.

That said, if somebody wants to pick this up as a quick project, modifying the ditherworker.js file for other types of dithering should not be too difficult.
